# Generated by Django 5.1 on 2024-08-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_admregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admregistration',
        ),
    ]
