# Generated by Django 5.1 on 2024-08-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_delete_tbl_admregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admregistration_name', models.CharField(max_length=30)),
                ('admregistration_email', models.CharField(max_length=30)),
                ('admregistration_password', models.CharField(max_length=30)),
            ],
        ),
    ]
