# Generated by Django 5.1 on 2024-08-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
    ]
