# Generated by Django 5.1 on 2024-08-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_shop',
        ),
    ]
