# Generated by Django 5.1 on 2024-08-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='product_photo',
            field=models.FileField(upload_to='Assets/Product'),
        ),
        migrations.AlterField(
            model_name='tbl_shop',
            name='shop_photo',
            field=models.FileField(upload_to='Assets/Shop'),
        ),
    ]
