# Generated by Django 5.1.1 on 2024-09-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_alter_tbl_product_product_photo_and_more'),
        ('ShopManager', '0013_delete_tbl_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_shop',
        ),
    ]
