# Generated by Django 5.1.1 on 2024-09-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_tbl_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='product_photo',
            field=models.FileField(upload_to='Assets/Product/'),
        ),
        migrations.AlterField(
            model_name='tbl_shop',
            name='shop_photo',
            field=models.FileField(upload_to='Assets/Shop/'),
        ),
    ]
