# Generated by Django 5.1 on 2024-08-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ShopManager', '0002_delete_tbl_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=30)),
                ('stock_quantity', models.CharField(max_length=30)),
            ],
        ),
    ]
