# Generated by Django 5.1 on 2024-08-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopManager', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
