# Generated by Django 5.1 on 2024-09-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopManager', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
