# Generated by Django 5.1 on 2024-09-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopManager', '0008_tbl_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
