# Generated by Django 5.1 on 2024-09-02 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_alter_tbl_product_product_photo_and_more'),
        ('ShopManager', '0009_delete_tbl_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=30)),
                ('stock_quantity', models.CharField(max_length=30)),
                ('stock_datetime', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_product')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_shop')),
            ],
        ),
    ]
