# Generated by Django 5.1 on 2024-09-10 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_alter_tbl_product_product_photo_and_more'),
        ('ShopManager', '0010_tbl_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField()),
                ('purchase_status', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopManager.tbl_customer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.IntegerField()),
                ('item_qty', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopManager.tbl_purchase')),
            ],
        ),
    ]
