# Generated by Django 5.1.1 on 2024-09-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopManager', '0012_alter_tbl_purchase_purchase_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
