# Generated by Django 5.0.6 on 2024-09-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopManager', '0014_tbl_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_purchase',
            name='customer',
        ),
        migrations.DeleteModel(
            name='tbl_items',
        ),
        migrations.DeleteModel(
            name='tbl_purchase',
        ),
    ]
