# Generated by Django 5.0.6 on 2024-09-19 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_alter_tbl_product_product_photo_and_more'),
        ('ShopManager', '0015_remove_tbl_purchase_customer_delete_tbl_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_status', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopManager.tbl_customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_shop')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.IntegerField()),
                ('item_qty', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopManager.tbl_purchase')),
            ],
        ),
    ]
