# Generated by Django 5.0.6 on 2024-09-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopManager', '0017_tbl_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
